In [1]:
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

In [2]:
import pandas as pd
data=pd.read_csv("disease_test_100.csv")
data

   Person      Actual   Predicted
0      P1     Disease     Disease
1      P2     Disease     Disease
2      P3     Disease  No Disease
3      P4     Disease  No Disease
4      P5  No Disease     Disease
..    ...         ...         ...
95    P96  No Disease  No Disease
96    P97  No Disease     Disease
97    P98  No Disease  No Disease
98    P99  No Disease  No Disease
99   P100  No Disease  No Disease

[100 rows x 3 columns]

In [4]:
le=LabelEncoder()
x=le.fit_transform(data["Actual"])
y=le.fit_transform(data["Predicted"])

In [5]:
x

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [6]:
y

array([0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1])

In [7]:
accuracy=accuracy_score(x,y)
precision=precision_score(x,y)
recall=recall_score(x,y)
f1=f1_score(x,y)
cm=confusion_matrix(x,y)

In [8]:
print("accuracy")
print(accuracy)
print("precision")
print(precision)
print("recall")
print(recall)
print("f1")
print(f1)
print("confusion matrix")
print(cm)

accuracy
0.76
precision
0.7391304347826086
recall
0.7391304347826086
f1
0.7391304347826086
confusion matrix
[[42 12]
 [12 34]]

In [9]:
import pandas as pd
data=pd.read_csv("customer_food_preferences_100.csv")
data

   Customer  Spicy  Cheese Likes Food
0        C1      1       0        Yes
1        C2      0       1        Yes
2        C3      1       1        Yes
3        C4      0       0         No
4        C5      1       0        Yes
..      ...    ...     ...        ...
95      C96      0       0         No
96      C97      1       0        Yes
97      C98      0       1        Yes
98      C99      1       1        Yes
99     C100      0       0         No

[100 rows x 4 columns]

In [15]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [14]:
spicy=data["Spicy"]
cheese=data["Cheese"]
x=np.column_stack([spicy,cheese])
x

array([[1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0]])

In [16]:
y=le.fit_transform(data["Likes Food"])
y

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [17]:
x_train,y_train,x_test,y_test= train_test_split(x,y,test_size=0.2)

In [18]:
model=BernoulliNB()
model.fit(x_train,x_test)

BernoulliNB()

In [19]:
spicy=int(input("enter your answer(1-yes,no-0):"))
cheese=int(input("enter your answer(1-yes,no-0):"))
test_food=np.array([spicy,cheese]).reshape(1,-1)
test_food
answer=model.predict(test_food)
print(answer)
print(le.inverse_transform(answer))

enter your answer(1-yes,no-0):1
enter your answer(1-yes,no-0):1
[1]
['Yes']

In [21]:
y_pred=model.predict(y_train)
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1])

In [24]:
cm=confusion_matrix(y_test,y_pred)
cm

array([[ 6,  0],
       [ 0, 14]])

In [25]:
f1=f1_score(y_test,y_pred)
f1

1.0

In [26]:
recall=recall_score(y_test,y_pred)
recall

1.0

In [27]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0