In [4]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import LabelEncoder

In [ ]:
data=pd.read_csv("email.csv")
data

                                                   text  spam
0     Subject: naturally irresistible your corporate...     1
1     Subject: the stock trading gunslinger  fanny i...     1
2     Subject: unbelievable new homes made easy  im ...     1
3     Subject: 4 color printing special  request add...     1
4     Subject: do not have money , get software cds ...     1
...                                                 ...   ...
5723  Subject: re : research and development charges...     0
5724  Subject: re : receipts from visit  jim ,  than...     0
5725  Subject: re : enron case study update  wow ! a...     0
5726  Subject: re : interest  david ,  please , call...     0
5727  Subject: news : aurora 5 . 2 update  aurora ve...     0

[5728 rows x 2 columns]

In [ ]:
emails=data["text"]
y=data["spam"]

In [ ]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(emails)

In [ ]:
model = MultinomialNB()
model.fit(X, y)

MultinomialNB()

In [ ]:
mail=input("Enter your mail words:")
test_email = [mail]
test_vec = vectorizer.transform(test_email)

pred = model.predict(test_vec)
print(pred)

Enter your mail words:hi dear,how are you?
[0]

In [ ]:
if pred==0:
  print("not spam")
else:
  print("spam")

not spam

In [ ]:
from sklearn.naive_bayes import GaussianNB
students_details=pd.read_csv("Pass.csv")
students_details

    id  subject1  subject2 Pass
0    0        32        50  yes
1    1        10        42   no
2    2        40        45  yes
3    3        55        10   no
4    4        35        50  yes
5    5        25        20   no
6    6        32        30   no
7    7        50        50  yes
8    8        35        35  yes
9    9        42        60  yes
10  10        39        30   no
11  11        20        30   no
12  12        10        50   no
13  13        45        10   no
14  14        45        45  yes
15  15        49        30  yes
16  16        12        50   no
17  17        49        49  yes
18  18        50        49  yes
19  19        30        22   no
20  20        15        35   no
21  21        19        43   no
22  22        48        12   no
23  23        45        25  yes

In [ ]:
sub1=students_details.loc[1:50,"subject1"]
x1=np.array(sub1)
x1

array([10, 40, 55, 35, 25, 32, 50, 35, 42, 39, 20, 10, 45, 45, 49, 12, 49,
       50, 30, 15, 19, 48, 45])

In [ ]:
sub2=students_details.loc[1:50,"subject2"]
x2=np.array(sub2)
x2

array([42, 45, 10, 50, 20, 30, 50, 35, 60, 30, 30, 50, 10, 45, 30, 50, 49,
       49, 22, 35, 43, 12, 25])

In [ ]:
add=x1+x2
total=np.array(add)
total

array([ 52,  85,  65,  85,  45,  62, 100,  70, 102,  69,  50,  60,  55,
        90,  79,  62,  98,  99,  52,  50,  62,  60,  70])

In [ ]:
X=np.array(total).reshape(-1,1)
X

array([[ 52],
       [ 85],
       [ 65],
       [ 85],
       [ 45],
       [ 62],
       [100],
       [ 70],
       [102],
       [ 69],
       [ 50],
       [ 60],
       [ 55],
       [ 90],
       [ 79],
       [ 62],
       [ 98],
       [ 99],
       [ 52],
       [ 50],
       [ 62],
       [ 60],
       [ 70]])

In [ ]:
y_text=students_details.loc[1:50,"Pass"]
y_text

1      no
2     yes
3      no
4     yes
5      no
6      no
7     yes
8     yes
9     yes
10     no
11     no
12     no
13     no
14    yes
15    yes
16     no
17    yes
18    yes
19     no
20     no
21     no
22     no
23    yes
Name: Pass, dtype: object

In [ ]:
le = LabelEncoder()
y = le.fit_transform(y_text)
y

array([0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1])

In [ ]:
model = GaussianNB()
model.fit(X, y)

GaussianNB()

In [ ]:
mark=int(input("Enter your mark:"))
test_mark=np.array(mark).reshape(-1,1)
test_mark
answer=model.predict(test_mark)
print(answer)
print(le.inverse_transform(answer))

Enter your mark:100
[1]
['yes']

In [1]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import LabelEncoder

In [5]:
ds=pd.read_csv("food_set.csv")
ds

   Customer  Spicy  Cheese Likes Food
0        C1      1       0        Yes
1        C2      0       1        Yes
2        C3      1       1        Yes
3        C4      0       0         No
4        C5      1       0        Yes
..      ...    ...     ...        ...
95      C96      0       0         No
96      C97      1       0        Yes
97      C98      0       1        Yes
98      C99      1       1        Yes
99     C100      0       0         No

[100 rows x 4 columns]

In [28]:
x1=ds["Spicy"]
x2=ds["Cheese"]
X=np.column_stack((x1,x2))
X

array([[1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [0, 0]])

In [20]:
y_text=ds["Likes Food"]
y_text

0     Yes
1     Yes
2     Yes
3      No
4     Yes
     ...
95     No
96    Yes
97    Yes
98    Yes
99     No
Name: Likes Food, Length: 100, dtype: object

In [21]:
le = LabelEncoder()
y = le.fit_transform(y_text)
y

array([1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0])

In [29]:
model=BernoulliNB()
model.fit(X,y)

BernoulliNB()

In [30]:
spicy=int(input("enter your answer(1-yes,no-0):"))
cheese=int(input("enter your answer(1-yes,no-0):"))
test_food=np.array([spicy,cheese]).reshape(1,-1)
test_food
answer=model.predict(test_food)
print(answer)
print(le.inverse_transform(answer))

enter your answer(1-yes,no-0):1
enter your answer(1-yes,no-0):0
[1]
['Yes']