In [2]:
import pandas as pd
import statsmodels.api as sm

from statsmodels.discrete.count_model import ZeroInflatedPoisson

In [3]:
df = pd.read_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [5]:
X = df[["age", "bmi"]]
X

      age     bmi
0      19  27.900
1      18  33.770
2      28  33.000
3      33  22.705
4      32  28.880
...   ...     ...
1333   50  30.970
1334   18  31.920
1335   18  36.850
1336   21  25.800
1337   61  29.070

[1338 rows x 2 columns]

In [6]:
y = df["children"]
y

0       0
1       1
2       3
3       0
4       0
       ..
1333    3
1334    0
1335    0
1336    0
1337    0
Name: children, Length: 1338, dtype: int64

In [7]:
X = sm.add_constant(X)
X

      const  age     bmi
0       1.0   19  27.900
1       1.0   18  33.770
2       1.0   28  33.000
3       1.0   33  22.705
4       1.0   32  28.880
...     ...  ...     ...
1333    1.0   50  30.970
1334    1.0   18  31.920
1335    1.0   18  36.850
1336    1.0   21  25.800
1337    1.0   61  29.070

[1338 rows x 3 columns]

In [8]:
model = ZeroInflatedPoisson(
    endog=y,
    exog=X,
    exog_infl=X
)

result = model.fit()

         Current function value: 1.376744
         Iterations: 35
         Function evaluations: 48
         Gradient evaluations: 48

/usr/local/lib/python3.12/dist-packages/scipy/optimize/_optimize.py:1330: OptimizeWarning: Maximum number of iterations has been exceeded.
  res = _minimize_bfgs(f, x0, args, fprime, callback=callback, **opts)
/usr/local/lib/python3.12/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

In [9]:
print(result.summary())

                     ZeroInflatedPoisson Regression Results
===============================================================================
Dep. Variable:                children   No. Observations:                 1338
Model:             ZeroInflatedPoisson   Df Residuals:                     1335
Method:                            MLE   Df Model:                            2
Date:                 Wed, 24 Jun 2026   Pseudo R-squ.:                 0.02340
Time:                         19:09:10   Log-Likelihood:                -1842.1
converged:                       False   LL-Null:                       -1886.2
Covariance Type:             nonrobust   LLR p-value:                 6.801e-20
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
inflate_const     4.9687      0.848      5.858      0.000       3.306       6.631
inflate_age      -0.2389      0.029     -8.166      0.000      -0.296      -0.182
inflate_bmi       0.0097      0.019      0.503      0.615      -0.028       0.048
const             0.8202      0.157      5.226      0.000       0.513       1.128
age              -0.0165      0.002     -7.527      0.000      -0.021      -0.012
bmi               0.0041      0.004      0.917      0.359      -0.005       0.013
=================================================================================

In [10]:
print(df["children"].value_counts())

children
0    574
1    324
2    240
3    157
4     25
5     18
Name: count, dtype: int64

In [11]:
zero_percentage = (df["children"] == 0).mean() * 100

print("Zero Percentage:", round(zero_percentage,2), "%")

Zero Percentage: 42.9 %

In [12]:
age = int(input("Enter Age: "))
bmi = float(input("Enter BMI: "))

new_data = pd.DataFrame({
    "const": [1],
    "age": [age],
    "bmi": [bmi]
})

prediction = result.predict(
    exog=new_data,
    exog_infl=new_data
)

print("Predicted Children:", round(prediction[0]))

Enter Age: 30
Enter BMI: 28.5
Predicted Children: 1